# Generated by Django 3.2.9 on 2022-05-20 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('location_lat', models.FloatField(default=0)),
                ('location_lon', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy')], default='AVAILABLE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_lat', models.FloatField(default=0)),
                ('location_lon', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ON_GOING', 'on-going'), ('FINISHED', 'Finished')], default='ON_GOING', max_length=10)),
                ('start_location_lat', models.FloatField(blank=True, null=True)),
                ('start_location_lon', models.FloatField(blank=True, null=True)),
                ('end_location_lat', models.FloatField(blank=True, null=True)),
                ('end_location_lon', models.FloatField(blank=True, null=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bike')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
