# Generated by Django 4.0.4 on 2022-05-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
